### ISSUE TITLE
fix upstream deprecations (after urlib3 2.0 release)

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/rest-tools#11]
https://github.com/WIPACrepo/rest-tools/blob/fee14ea3ec717bf1ebe2f08e6581bfc611f5c821/rest_tools/client/session.py#L35
`method_whitelist` is now deprecated, in favor of `allowed_methods`.

**Comment by ric-evans** [comment]
Punting until **urlib3 2.0** is released to PyPi ([see roadmap](https://urllib3.readthedocs.io/en/latest/v2-roadmap.html)) 

`requests.packages.urllib3.util.retry` is a wrapper around `urllib3.util.retry`, the wrapper currently works. At some point after urlib3 2.0 I imagine requests will follow suit and deprecate this wrapper

**Comment by ric-evans** [comment]
> mid-to-late 2021
