### ISSUE TITLE
ArgumentHandler: Add Type-Checking for Body Arguments

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/rest-tools#12]
@blinkdog discovered in the wild that it would be useful to check types for `request.body` arguments. Also, gotchas may arise since body arguments retain type info over the wire.

Currently:
- If `get_argument("body-arg-1", type_=list)` parses a body argument, `"mystr"` could be parsed as `["m","y","s","t","r"]`. This could be useful for base-query arguments (unlikely), but not body arguments (definitely).
- Meanwhile `get_body_argument()` does not have `type_`.

Proposal:
- If `get_argument("body-arg-1", type_=list)` parses a body argument, and the argument is not a list (say `"mystr"`) it will raise a `400` error.
- `get_body_argument()` will act similarly by adding `type_` (optional).

**Comment by dsschult** [comment]
Note that query arguments do have some vague type support, in the sense you can specify more than one to get a list.  and the file catalog has that system of nested keys to make dicts.  still have to parse for int and float, but that's a simple test.

**Comment by ric-evans** [comment]
The beast that is backwards compatibility :grimacing: I'm aware of what's happening in the file catalog, and I plan to approach that cautiously from a great distance.

But yes, `type_` is optional so it's designed to be friendly in these scenarios

**Comment by blinkdog** [comment]
So the current API looks like this:
```python
    def get_json_body_argument(
        self,
        name: str,
        default: Any = arghandler.NO_DEFAULT,
        choices: Optional[List[Any]] = None,
    ) -> Any:
```
```python
    def get_argument(
        self,
        name: str,
        default: Any = arghandler.NO_DEFAULT,
        strip: bool = True,
        type_: Optional[type] = None,
        choices: Optional[List[Any]] = None,
    ) -> Any:
```

Maybe consider this for an API?

```python
    def get_argument(
        self,
        name: str,
        default: Any = arghandler.NO_DEFAULT,
        strip: bool = True,
        not_empty: bool = False,
        check_for: Optional[type] = None,
        cast_as: Optional[type] = None,
        choices: Optional[List[Any]] = None,
    ) -> Any:
```

`type_` here becomes `cast_as`, which operates the same.
`check_for` is a hard check of the type, before any casting/conversion
`not_empty` throws on empty string / dict / list when `True`

**Comment by ric-evans** [comment]
I understand the want to separate `type_` into `check_for` and `cast_as`, but ultimate they serve the same purpose: make sure whatever I get is a "this"-type. 

`not_empty` is interesting, I'm leaning towards `invalid_choices` to make it apply to none string/dict/list values.

@blinkdog let's move the conversation to https://github.com/WIPACrepo/rest-tools/pull/13
