### ISSUE TITLE
Move `from_environment()` to New Repo

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/rest-tools#25]
We need to resolve this circular dependency: WIPAC Telemetry needs to use `from_environment()`, but rest-tools needs to import WIPAC Telemetry.

I propose "wipac-tools", a repo where we can place utility functions that rely on no other WIPAC repos.

We'll need to add redirects in the existing [py module](https://github.com/WIPACrepo/rest-tools/blob/master/rest_tools/server/config.py) for backwards compatibility.

**Comment by dsschult** [comment]
maybe `wipac-dev-tools`?

**Comment by ric-evans** [comment]
Alternatively, we call it "env-tools". This looks to be a pattern we've made in the past.

**Comment by dsschult** [comment]
I mostly don't want it to be too generic, since we're not the only user of WIPACrepo.

**Comment by ric-evans** [comment]
Makes sense. `wipac-dev-tools` fits

**Comment by ric-evans** [comment]
reopening

**Comment by ric-evans** [comment]
We'll also need to add a redirect in `rest_tools/server/config.py` with `legacy_bool=True` for backward compatibility.
