### ISSUE TITLE
telemetry is imported even when not needed

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/rest-tools#52]
Trying to start a script that only uses `Auth` and `from_environment` (no tracing), it fails with this:

```python
[wipac-telemetry-setup] Setting Tracer Provider...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wipac_telemetry/tracing_tools/__init__.py",
 line 94, in get_service_name
    main_mod_abspath = Path(os.path.abspath(main_mod.__file__))
AttributeError: module '__main__' has no attribute '__file__'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "webapp/app.py", line 13, in <module>
    from reco_api import api_high_level
  File "/home/app/./reco_api/api_high_level.py", line 3, in <module>
    from rest_tools.server import Auth, from_environment
  File "/src/rest-tools/rest_tools/server/__init__.py", line 6, in <module>
    from .handler import (
  File "/src/rest-tools/rest_tools/server/handler.py", line 16, in <module>
    import wipac_telemetry.tracing_tools as wtt
  File "/usr/local/lib/python3.9/site-packages/wipac_telemetry/__init__.py", line 3, in <m
odule>
    from . import tracing_tools  # noqa
  File "/usr/local/lib/python3.9/site-packages/wipac_telemetry/tracing_tools/__init__.py",
 line 128, in <module>
    TracerProvider(resource=Resource.create({SERVICE_NAME: get_service_name()}))
  File "/usr/local/lib/python3.9/site-packages/wipac_telemetry/tracing_tools/__init__.py",
 line 96, in get_service_name
    raise WIPACTelemetryStartupError(
wipac_telemetry.tracing_tools.WIPACTelemetryStartupError: Service started up before '__mai
n__' was set. Do you have imports in your package's base '__init__.py'? If so, remove them
; one of these likely prematurely called this library before '__main__.py' was executed. A
lternatively, are in a REPL (like iPython)? WIPACTEL doesn't support tracing REPLs.
```

**Comment by dsschult** [comment]
As a note, this is a wsgi script, started with uwsgi.  So, not sure how it handles `__main__`.

**Comment by ric-evans** [comment]
Do you want tracing enabled in this case? This can only happen if you have `WIPACTEL_EXPORT_STDOUT` or `OTEL_EXPORTER_OTLP_ENDPOINT` set.

**Comment by dsschult** [comment]
No, I don't need tracing.

**Comment by dsschult** [comment]
It might be something nice to think about in the future, but not required right now.

**Comment by dsschult** [comment]
For this, I just find it problematic that tracing attempts to load (and fails) even when I'm not using anything related to it.

**Comment by ric-evans** [comment]
https://github.com/WIPACrepo/wipac-telemetry-prototype/blob/main/wipac_telemetry/tracing_tools/__init__.py#L128

This isn't a bug. One of those environment variables has to be set for it to attempt to load what it does.

Now, if we're talking about not even loading the WIPACTEL package dynamically, that's an enhancement. Which I agree, could be useful.

**Comment by dsschult** [comment]
Ah, I had `OTEL_EXPORTER_OTLP_ENDPOINT` copied from another place in the k8s yaml.  Works without that.

**Comment by ric-evans** [comment]
### Next Steps
- Don't put wipactel package in `requirements.txt`/`required_packages`
   - add try-except around all `import` statements: use dummy module if `ImportError`
   - Example:
```python3
try:
	from wipac_telemetry import tracing as wtt
except ImportError:
	wtt = DummyTracingModule
```

### Gotchas and Other Radical Ideas
- What if tracing is wanted (aka an environment variable is set) but the package isn't installed?
	- preferably, an Exception would be raised alerting the client
	- is it possible to detect telemetry is wanted without having to keep a list of the wipactel environment variables in `rest-tools`? We want to keep redundancy to a minimum considering future wipactel developments.
- How does the client know what version of the package to install if it's not in requirements.txt?
	- Is it kosher to add functionality based on the presence of a package? _Probably_ 
- How about we add a wrapper package (like the `MQClient`-implementation [packages](https://github.com/WIPACrepo/MQClient-GCP)) called `rest-tools-telemetrized` which moves all telemetry instrumentation to its own repo with calls to the "real" `rest-tools`
	- @blinkdog we discussed a similar idea earlier this week

**Comment by dsschult** [comment]
I think one of the "issues" at play here is that we're getting all the imports for the server handlers, even if we never use a handler.  Maybe a more local import of telemetry in that file, instead of the global import?

**Comment by ric-evans** [comment]
> I think one of the "issues" at play here is that we're getting all the imports for the server handlers, even if we never use a handler. Maybe a more local import of telemetry in that file, instead of the global import?

I don't think we can prevent global imports since the submodules are imported by their parent module. I believe that's what's happening currently: local imports become global imports.

> The other option I guess is to stop doing `__init__.py` level imports of classes, at least in this case.

This could work. OTEL keeps a global variable that more-or-less tracks whether tracing has been activated. We would need to add a precondition to each wipactel method/function/decorator that checks if activation is needed before preceding.

**Comment by dsschult** [comment]
I'm just wondering if something like:

```python
class Handler:
    def __init__(self):
        import telementry
    # more code here
```

might work.  It means telemetry is only imported if the class is ever instantiated.

**Comment by ric-evans** [comment]
That is much simpler. It solves Gotcha 1 (https://github.com/WIPACrepo/rest-tools/issues/52#issuecomment-972286616) but leaves Gotcha 2.

**Comment by ric-evans** [comment]
@dsschult you were right in the sprint meeting, importing in `__init__()` won't work with decorators since class methods are built out at startup.

**Comment by dsschult** [comment]
> @dsschult you were right in the sprint meeting, importing in `__init__()` won't work with decorators since class methods are built out at startup.

Yeah, I was afraid of that.

**Comment by dsschult** [comment]
So the only other solution is to stop importing the handler in `__init__.py` and forcing people to do 
```python
from rest_tools.server.handler import RestHandler
```

Or I guess we could think of reorganizing rest_tools, since the `Auth` is more commonly used outside the server.

**Comment by ric-evans** [comment]
I'm not sure there's a band-aid solution here. I'm a fan of making a wrapper repo/package with telemetry instrumentation. The other option is to go this [route](https://stackoverflow.com/questions/5122465/can-i-fake-a-package-or-at-least-a-module-in-python-for-testing-purposes/45421428) and fake the package, but that'll require a good amount of code to fake everything correctly.

**Comment by ric-evans** [comment]
> So the only other solution is to stop importing the handler in `__init__.py` and forcing people to do
> 
> ```python
> from rest_tools.server.handler import RestHandler
> ```
> 
> Or I guess we could think of reorganizing rest_tools, since the `Auth` is more commonly used outside the server.

Both of these will cause a good amount of backwards incompatibility. It could be worth it. Would Auth be be its own sub-package like client, server, and utils?

**Comment by dsschult** [comment]
> > So the only other solution is to stop importing the handler in `__init__.py` and forcing people to do
> > ```python
> > from rest_tools.server.handler import RestHandler
> > ```
> >   
> > Or I guess we could think of reorganizing rest_tools, since the `Auth` is more commonly used outside the server.
> 
> Both of these will cause a good amount of backwards incompatibility. It could be worth it. Would Auth be be its own sub-package like client, server, and utils?

I'd probably put Auth in utils.  I guess if you didn't want to break compatibility, you could re-import it in the server.

But this at least means you could get to non-server functionality without importing telemetry.

**Comment by dsschult** [comment]
I might actually consider putting all of these in util:

```python
from .auth import Auth, OpenIDAuth
from .config import from_environment
from .daemon import Daemon
```
